version: "3.7"

services:
  web:
    image: bentenants-scheduler
    hostname: bentenants-scheduler
    ports:
      - target: 5000
        published: 5050
        protocol: tcp
    volumes:
      - type: volume
        source: /
    networks:
      - bentenants

  mongo:
    image: mongo:4.1
    hostname: mongodb
    container_name: mongodb
    restart: always
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - type: volume
        source: /data/db
        target: /data/db
    networks:
      - bentenants
    command: mongod --noauth

networks:
  bentenants:
